[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#141413"
backgroundColor = "#F0EEE6"
secondaryBackgroundColor = "#E3DACC"
textColor = "#141413"
font = "sans serif"
